---

- name: Install Prerequisites
  apt:
    name:
      - software-properties-common
      - python3-launchpadlib
    state: present
    update_cache: yes

- name: Add PHP PPA
  apt_repository:
    repo: ppa:ondrej/php
    state: present
    update_cache: yes
  register: result
  until: result is success
  retries: 3
  delay: 10

- name: Install Stack
  apt:
    name:
      - nginx
      - "php{{ php_version }}-fpm"
      - "php{{ php_version }}-cli"
      - "php{{ php_version }}-mysql"
      - "php{{ php_version }}-zip"
      - "php{{ php_version }}-gd"
      - "php{{ php_version }}-mbstring"
      - "php{{ php_version }}-curl"
      - "php{{ php_version }}-xml"
      - "php{{ php_version }}-bcmath"
      - unzip
      - git
      - acl
    state: present
    update_cache: true


- name: Install Composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer


- name: Create Dir
  file:
    path: "{{ app_dir }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Remove Existing App Dir
  file:
    path: "{{ app_dir }}"
    state: absent

- name: Clone Repo
  git:
    repo: "{{ repo_url }}"
    dest: "{{ app_dir }}"
    version: "{{ repo_branch }}"
    update: no
  become: yes

- name: Fix Perms
  file:
    path: "{{ app_dir }}"
    owner: www-data
    group: www-data
    recurse: yes

- name: Install Deps
  command: composer install --no-interaction --prefer-dist --optimize-autoloader --no-cache
  args:
    chdir: "{{ app_dir }}"
  become: yes
  become_user: www-data


- name: Setup .env
  copy:
    src: "{{ app_dir }}/.env.example"
    dest: "{{ app_dir }}/.env"
    remote_src: yes
    owner: www-data
    group: www-data
    force: no

- name: Generate Key
  shell: grep -q "APP_KEY=base64" .env || php artisan key:generate
  args:
    chdir: "{{ app_dir }}"
  become: yes
  become_user: www-data




- name: Writable Dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0775'
    recurse: yes
  loop:
    - "{{ app_dir }}/storage"
    - "{{ app_dir }}/bootstrap/cache"

- name: Clean Nginx
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart Nginx

- name: Config Nginx
  template:
    src: laravel.conf.j2
    dest: /etc/nginx/sites-available/laravel
    owner: root
    group: root
    mode: '0644'
  notify: Restart Nginx

- name: Enable Site
  file:
    src: /etc/nginx/sites-available/laravel
    dest: /etc/nginx/sites-enabled/laravel
    state: link
  notify: Restart Nginx

- name: Migrate DB
  command: php artisan migrate --force
  args:
    chdir: "{{ app_dir }}"
  become: yes
  become_user: www-data